"""AIR SLOT sequential decision-chain reference implementation.

The package implements the manuscript chain without claiming causal action
effects, observed monetary loss, or historical-policy optimality.
"""

from .action_response import (
    ActionEligibility,
    ActionResponseRule,
    ActionTemplate,
    EligibilityState,
    ResponseSupport,
    materialize_action,
)
from .contracts import (
    CONSEQUENCE_COMPONENTS,
    CUComponent,
    ConsequenceScenario,
    HistoryConditionedState,
    NativeConsequenceComponent,
    OperationalInformation,
    SupportState,
)
from .pipeline import DecisionChainInput, DecisionChainOutput, run_decision_chain
from .risk import (
    MappingStatus,
    RMBMappingRegistry,
    ResidualRiskPolicy,
    RiskPolicyStatus,
    evaluate_residual_risk,
)
from .experiments import (
    EXP1_VARIANTS,
    EXP2_VARIANTS,
    EXP3_VARIANTS,
    EXP4_VARIANTS,
    EXP4_DATA1_RUN_ACCEPTABILITY,
    Data1Acceptance,
    ExperimentManifest,
    ExperimentStage,
    SafetyState,
    build_experiment_manifest,
    development_protocol_report,
    validate_representation_isolation,
    build_data1_acceptance_report,
)
from .workflow import (
    WorkflowManifest,
    WorkflowStageRecord,
    WorkflowStageStatus,
    build_development_workflow_manifest,
    build_contract_audit,
    build_artifact_manifest,
    build_experiment_readiness,
    build_validation_report,
    write_development_manifest,
    write_contract_audit,
    write_artifact_manifest,
    write_experiment_readiness,
    write_data1_acceptance,
    write_validation_report,
)

__all__ = [
    "ActionEligibility",
    "ActionResponseRule",
    "ActionTemplate",
    "CONSEQUENCE_COMPONENTS",
    "CUComponent",
    "ConsequenceScenario",
    "DecisionChainInput",
    "DecisionChainOutput",
    "EligibilityState",
    "HistoryConditionedState",
    "MappingStatus",
    "NativeConsequenceComponent",
    "OperationalInformation",
    "RMBMappingRegistry",
    "ResidualRiskPolicy",
    "ResponseSupport",
    "RiskPolicyStatus",
    "SupportState",
    "evaluate_residual_risk",
    "materialize_action",
    "run_decision_chain",
    "EXP1_VARIANTS",
    "EXP2_VARIANTS",
    "EXP3_VARIANTS",
    "EXP4_VARIANTS",
    "EXP4_DATA1_RUN_ACCEPTABILITY",
    "Data1Acceptance",
    "ExperimentManifest",
    "ExperimentStage",
    "SafetyState",
    "build_experiment_manifest",
    "development_protocol_report",
    "validate_representation_isolation",
    "build_data1_acceptance_report",
    "WorkflowManifest",
    "WorkflowStageRecord",
    "WorkflowStageStatus",
    "build_development_workflow_manifest",
    "build_contract_audit",
    "build_artifact_manifest",
    "build_experiment_readiness",
    "build_validation_report",
    "write_development_manifest",
    "write_contract_audit",
    "write_artifact_manifest",
    "write_experiment_readiness",
    "write_data1_acceptance",
    "write_validation_report",
]
